---
version: "2.1"
services:
  headphones:
    image: lscr.io/linuxserver/headphones:latest
    container_name: headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /encrypted/docker/headphones/config:/config
      - /downloads:/downloads
      - /encrypted/music:/music
    ports:
      - 8181:8181
    restart: unless-stopped
